### ISSUE TITLE
Image for README.md

### ISSUE THREAD

**Issue by HampusHauffman** [HampusHauffman/bionic.nvim#1]
<img width="1728" alt="Screenshot 2023-05-26 at 18 01 59" src="https://github.com/HampusHauffman/bionic.nvim/assets/3845743/bee49a5a-1a92-495b-988a-589eded10de2">

**Comment by HampusHauffman** [comment]
<img width="1096" alt="Screenshot 2023-05-26 at 18 08 20" src="https://github.com/HampusHauffman/bionic.nvim/assets/3845743/8ebb44af-9a59-43f6-b80a-4ea24c452f1a">

**Comment by HampusHauffman** [comment]
DONZO

**Comment by HampusHauffman** [comment]
<img width="857" alt="Screenshot 2023-05-26 at 22 36 36" src="https://github.com/HampusHauffman/bionic.nvim/assets/3845743/ef7be9fe-c91c-4c01-bb61-2e0b261bdffb">

**Comment by OmiChrome** [comment]
which font is this ? 
i use [maple-mono](https://github.com/subframe7536/Maple-font) but din't have any result as your showing!
